[tool.poetry]
name = "vector-db-benchmark"
version = "0.1.0"
description = ""
authors = ["Qdrant Team <info@qdrant.tech>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
typer = {extras = ["rich"], version = "^0.12.3"}
requests = "^2.31.0"
qdrant-client = "^1.9.2"
# We use custom fork of weaviate-client because of
# https://github.com/weaviate/weaviate-python-client/issues/431
weaviate-client = "^4.6.4"
pymilvus = "^2.4.1"
redis = "^5.0.1"
elasticsearch = "^8.11.0"
psycopg = {version = "^3.1.12", extras = ["binary"]}
numpy = "^1.26.2"
h5py = "^3.10.0"
stopit = "^1.1.2"
prometheus-client = "^0.19.0"
pandas = "^2.1.4"
ujson = "^5.9.0"
python-ulid = "^2.0.0"
click = "8.1.7"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
pytest = "^7.1"
ipython = "^8.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
