version: '3.7'

services:
  qdrant_bench:
    image: ${CONTAINER_REGISTRY:-docker.io}/qdrant/qdrant:${QDRANT_VERSION}
    container_name: qdrant-continuous
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ci_datasets:/code/datasets
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 25Gb

volumes:
  ci_datasets:
    name: "ci_datasets"
