version: "3.7"

services:
  redis:
    image: redislabs/redisearch:latest
    #cgroup_parent: ex.slice
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 10m
